### ISSUE TITLE
em.gro doesnot exist or is not accessible

### ISSUE THREAD

**Issue by knabenphysik** [twistcode/twistcode-uitm-gromacs#4]
for step(8): gmx mdrun -v -deffnm em
for step (9) : gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr

I'm having error:

![error](https://user-images.githubusercontent.com/41872606/155933501-7bcb2abc-fdee-47d3-b202-001ccc36c6fd.png)

**Comment by sitiazma** [comment]
The error occurred during the first command. It is supposed to get the output em.gro, but due to some reasons it failed.

**Comment by knabenphysik** [comment]
@sitiazma : happy to report that gromacs on GPU can now run properly

- the culprit was mpi, we need to compile gromacs with -DGMX_MPI=ON (i've update the [guide](https://github.com/twistcode/twistcode-uitm-gromacs/blob/main/02_setup_gromacs_config_with_CUDA.md))

-  also, the process must run thru RDP (not terminal)
![Screenshot 2022-03-28 154608](https://user-images.githubusercontent.com/41872606/160353408-d5604dd4-5fc9-4bbb-9762-521578d69c13.png)
